"""운영자 시리얼 장치 포트.

발급/입장 두 장치를 분리했던 구조에서 단일 OperatorDevice 로 통합. 시그니처는 동일하게
유지 (`wake_wristband / signal_pass / signal_deny / clear_wristband`).
"""
from __future__ import annotations

from typing import Optional, Protocol, runtime_checkable


@runtime_checkable
class IOperatorDevice(Protocol):
    @property
    def is_connected(self) -> bool: ...
    @property
    def port(self) -> Optional[str]: ...

    async def connect(self, port: str) -> bool: ...
    def disconnect(self) -> None: ...

    async def wake_wristband(self) -> bool: ...
    async def signal_pass(self) -> bool: ...
    async def signal_deny(self) -> bool: ...
    async def clear_wristband(self) -> bool: ...
